apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example:ca-controller
rules:
- apiGroups:
  - network.example.com
  resources:
  - networkattachments
  verbs:
  - list
  - watch
  - update